twilio/twilio-verify-ios

- fastlane/Fastfile
- Rearranged fastfile steps to match github tag with latest commit in main
-  chore: Rearranged fastfile steps to match github tag with latest commit in main
> [housekeeping] - Rearranged fastfile steps to match github tag with latest commit in main

- TwilioVerifyDemo/TwilioVerifyDemo/FactorList/View/FactorListViewController.swift
- Fixes DemoApp compilation
- chore: Fixed DemoApp compilation
> [Housekeeping] - Fixed DemoApp compilation

- README.md
- TwilioVerify.xcodeproj/project.pbxproj
- TwilioVerify/TwilioVerify/Sources/Data/Storage.swift
- TwilioVerify/TwilioVerify/Sources/Domain/Factor/FactorFacade.swift
- TwilioVerify/TwilioVerify/Sources/Domain/Factor/FactorRepository.swift
- TwilioVerify/TwilioVerify/Sources/Domain/Factor/PushFactory.swift
- TwilioVerify/TwilioVerify/Sources/Domain/Manager/TwilioVerify.swift
- TwilioVerify/TwilioVerify/Sources/Domain/Manager/TwilioVerifyManager.swift
- TwilioVerifyDemo/TwilioVerifyDemo/TwilioVerify/TwilioVerifyAdapter.swift
- TwilioVerifyTests/TwilioVerify/Sources/Data/Mocks/StorageProviderMock.swift
- TwilioVerifyTests/TwilioVerify/Sources/Data/StorageTests.swift
- TwilioVerifyTests/TwilioVerify/Sources/Domain/Factor/FactorFacadeTests.swift
- TwilioVerifyTests/TwilioVerify/Sources/Domain/Factor/FactorRepositoryTests.swift
- TwilioVerifyTests/TwilioVerify/Sources/Domain/Factor/Mocks/FactorRepositoryMock.swift
- TwilioVerifyTests/TwilioVerify/Sources/Domain/Factor/Mocks/PushFactoryMock.swift
- TwilioVerifyTests/TwilioVerify/Sources/Domain/Factor/PushFactoryTests.swift
- TwilioVerifyTests/TwilioVerify/Sources/Domain/Manager/Mocks/FactorFacadeMock.swift
- TwilioVerifyTests/TwilioVerify/Sources/Domain/Manager/TwilioVerifyManagerTests.swift
- TwilioVerifyTests/TwilioVerify/Sources/Integration/TwilioVerifyTests.swift
Reverts twilio/twilio-verify-ios#108
> Revert "Version 0.2.0"

- TwilioVerifyDemo/TwilioVerifyDemo/Common/AppDelegate.swift
- [Housekeeping] - Fixes Issue when presenting Challenge screen from a push notification
-  Fixes Issue when presenting Challenge screen from a push notification
> [Housekeeping] - Fixes Issue when presenting Challenge screen from a push notification

- README.md
- TwilioVerify/TwilioVerify/Sources/Logger/Logger.swift
- ACCSEC-19719
- Add logging info to the README.md
> [ACCSEC-19719] Add logging documentation

- TwilioVerifyDemo/TwilioVerifyDemo/CreateFactor/Presenter/CreateFactorPresenter.swift
- ACCSEC-20143
- Validate push token before creating factor
> ACCSEC-20143 Validate device token for push

- TwilioVerifyDemo/TwilioVerifyDemo/Common/AppDelegate.swift
- Change notification info reading
> Change challenge info reading from push

- .circleci/config.yml
> Fix app distribution

- README.md
- TwilioVerify/TwilioVerify/Sources/TwilioVerifyError.swift
- ACCSEC-20438
- Use new range 604XX of error codes
-  fix: Update error codes
> [ACCSEC-20438] Update error codes

- TwilioVerifyDemo/TwilioVerifyDemo/Common/View/Base.lproj/Main.storyboard
- TwilioVerifyDemo/TwilioVerifyDemo/FactorDetail/View/ChallengeTableViewCell.xib
- TwilioVerifyDemo/TwilioVerifyDemo/FactorList/View/FactorTableViewCell.xib
- ACCSEC-19733
- Add accessibility identifiers for testing
> ACCSEC-19733 Accessibility identifiers for testing

- fastlane/Fastfile
> Update FTL devices

- TwilioVerify.xcodeproj/project.pbxproj
- ACCSEC-
- ISSUE-
- Remove team's placeholderID.
-
> [Xcode 12 Migration] - Remove team's placeholderID.

- TwilioVerifyDemo/TwilioVerifyDemo/Common/View/Base.lproj/Main.storyboard
> Change accessibility identifiers

- README.md
- ACCSEC-
- ISSUE-
- Clarify import at Readme file, for the upcoming version 1.0.0
-
> [SDK Renaming] - Readme Updates

- AppSizer/AppSizer/AppDelegate.swift
- Scripts/bump-version.swift
- TwilioVerifySDK/Info.plist
- ACCSEC-
- ISSUE-
- Revert CFBundleVersion
-
> [SDK Renaming] - Fix CFBundleVersion

- TwilioVerifySDK/TwilioVerify/Sources/Domain/Manager/TwilioVerify.swift
- TwilioVerifySDK/TwilioVerify/Sources/Networking/Models/Response.swift
- TwilioVerifySDK/TwilioVerify/Sources/Networking/NetworkProvider.swift
ACCSEC-21550
- Make public the method for setNetworkProvider & setBaseURL, since both are required by each other.
-
> [ACCSEC-21550] - Expose SetNetworkProvider in SDK Builder.

- .circleci/config.yml
- TwilioVerifyDemo/TwilioVerifyDemo/Common/View/Base.lproj/Main.storyboard
- TwilioVerifyDemo/TwilioVerifyDemo/FactorDetail/View/ChallengeTableViewCell.xib
- TwilioVerifyDemo/TwilioVerifyDemo/FactorList/View/FactorTableViewCell.xib
- fastlane/Fastfile
- ACCSEC-21712
- Update view identifiers
> ACCSEC-21712 Update view identifiers

- .gitignore
- TwilioVerifyDemo/TwilioVerifyDemo/FactorDetail/Presenter/FactorDetailPresenter.swift
- TwilioVerifySDK/TwilioVerify/Sources/API/ChallengeAPIClient.swift
- TwilioVerifySDK/TwilioVerify/Sources/Domain/Challenge/ChallengeFacade.swift
- TwilioVerifySDK/TwilioVerify/Sources/Domain/Challenge/ChallengeRepository.swift
- TwilioVerifySDK/TwilioVerify/Sources/Models/ChallengeListPayload.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/API/ChallengeAPIClientTests.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/API/Mocks/ChallengeAPIClientMock.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/Domain/Challenge/Mocks/ChallengeProviderMock.swift
- fastlane/Fastfile
- ACCSEC-22011
- Add order parameter to get challenge list
-  feat: Ordering for challenge list
> ACCSEC-22011 challenges order

- .gitignore
- TwilioVerifyDemo/TwilioVerifyDemo/FactorDetail/Presenter/FactorDetailPresenter.swift
- TwilioVerifySDK/TwilioVerify/Sources/API/ChallengeAPIClient.swift
- TwilioVerifySDK/TwilioVerify/Sources/Domain/Challenge/ChallengeFacade.swift
- TwilioVerifySDK/TwilioVerify/Sources/Domain/Challenge/ChallengeRepository.swift
- TwilioVerifySDK/TwilioVerify/Sources/Models/ChallengeListPayload.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/API/ChallengeAPIClientTests.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/API/Mocks/ChallengeAPIClientMock.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/Domain/Challenge/Mocks/ChallengeProviderMock.swift
- fastlane/Fastfile
> Version 1.1.0

- README.md
- TwilioVerifyDemo/TwilioVerifyDemo.xcodeproj/project.pbxproj
- TwilioVerifyDemo/TwilioVerifyDemo/Common/AppDelegate.swift
- TwilioVerifyDemo/TwilioVerifyDemo/Common/AppModel.swift
- TwilioVerifyDemo/TwilioVerifyDemo/Common/PushChallengePayloadData.swift
- TwilioVerifyDemo/TwilioVerifyDemo/Common/View/Base.lproj/Main.storyboard
- TwilioVerifyDemo/TwilioVerifyDemo/FactorDetail/Presenter/FactorDetailPresenter.swift
- TwilioVerifyDemo/TwilioVerifyDemo/FactorDetail/View/ChallengeTableViewCell.swift
- TwilioVerifyDemo/TwilioVerifyDemo/FactorDetail/View/ChallengeTableViewCell.xib
- TwilioVerifyDemo/TwilioVerifyDemo/FactorDetail/View/FactorDetailViewController.swift
- TwilioVerifyDemo/TwilioVerifyDemo/FactorList/View/FactorListViewController.swift
- ACCSEC-22261
n/a
- AppDelegate updated in order to handle Push challenges that are configured to automatically being approved against the VerifySDK.
- Switch added to UI on every factor to control the capability of silently approve every challenge.
- Readme updated.
-  
https://user-images.githubusercontent.com/14830877/133294470-893b7eb0-98c5-48ad-bfff-a6f3e80b34f0.MP4
> [ACCSEC-22261] Silent approvals supported in foreground for DemoApp

- README.md
- TwilioVerifySDK/TwilioVerify/Sources/Domain/Manager/TwilioVerify.swift
- ACCSEC-22363
- Make setClearStorageOnReinstall public 
- Add documentation for reinstall in readme
-  feat: Allow persisting factors after reinstall
> [ACCSEC-22363] Make setClearStorageOnReinstall public and add documentation

- TwilioVerifySDK.xcodeproj/project.pbxproj
- TwilioVerifySDK/TwilioSecurity/Sources/Storage/AuthenticatedSecureStorage.swift
- TwilioVerifySDKTests/TwilioSecurity/Sources/Storage/AuthenticatedSecureStorageTests.swift
- TwilioVerifySDKTests/TwilioSecurity/Sources/Storage/Mocks/AuthenticatorMock.swift
- TwilioVerifySDKTests/TwilioSecurity/Sources/Storage/Mocks/MockContext.swift
- fastlane/Fastfile
ACCSEC-22226
- ISSUE-
- Add AuthenticatedSecureStorageTests.
- Add MockContext.
- Add AuthenticatorMock.
- Evaluate authentication policy for Save & Get Data.
-
> [ACCSEC-22226] - AuthenticatedSecureStorage Tests

- TwilioVerifySDK/TwilioSecurity/Sources/Biometrics/BiometricError.swift
- TwilioVerifySDK/TwilioSecurity/Sources/Storage/AuthenticatedSecureStorage.swift
- TwilioVerifySDKTests/TwilioSecurity/Sources/Keychain/KeychainQueryTests.swift
- TwilioVerifySDKTests/TwilioSecurity/Sources/Keychain/KeychainTests.swift
- TwilioVerifySDKTests/TwilioSecurity/Sources/Keychain/Mocks/KeychainMock.swift
- TwilioVerifySDKTests/TwilioSecurity/Sources/Storage/AuthenticatedSecureStorageTests.swift
- TwilioVerifySDKTests/TwilioSecurity/Sources/Storage/Mocks/MockContext.swift
- TwilioVerifySDKTests/TwilioSecurity/Sources/Storage/Mocks/StubLAContext.swift
- [22994] - Proper BiometricDidChange Validation.
- ISSUE-
- Store the biometricPolicyState associated with the item in the keychain.
- Validate the current biometricPolicyState against the stored one to verify if there was a change.
-
> [22994] - Proper BiometricDidChange Validation.

- TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/FactorMapper.swift
- TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/Models/DTOs/PushFactorDTO.swift
- TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/Models/PushFactor.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/Domain/Factor/FactorMapperTests.swift
> Store notification platform

- README.md
- TwilioVerifyDemo/TwilioVerifyDemo.xcodeproj/project.pbxproj
- TwilioVerifyDemo/TwilioVerifyDemo/AccessToken/AccessTokensAPI.swift
- TwilioVerifyDemo/TwilioVerifyDemo/CreateFactor/Presenter/CreateFactorPresenter.swift
- TwilioVerifySDK.xcodeproj/project.pbxproj
- TwilioVerifySDK/TwilioVerify/Sources/API/BaseAPIClient.swift
- TwilioVerifySDK/TwilioVerify/Sources/API/FactorAPIClient.swift
- TwilioVerifySDK/TwilioVerify/Sources/Extensions/URLSession+Extensions.swift
- TwilioVerifySDK/TwilioVerify/Sources/Networking/Error/NetworkError.swift
- TwilioVerifySDK/TwilioVerify/Sources/TwilioVerifyError.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/API/ChallengeAPIClientTests.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/API/FactorAPIClientTests.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/Networking/NetworkAdapterTests.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/Networking/NetworkErrorTests.swift
- [22264]
- Internal `NetworkError` set as visible to developer.
- Sample app `NetworkError` renamed to prevent files conflict.
- Unit test updated.
- Example added for customers
-  fix: Improved network error to get Verify API error
> fix: Improved network error to get Verify API error

- README.md
- TwilioVerifyDemo/TwilioVerifyDemo.xcodeproj/project.pbxproj
- TwilioVerifyDemo/TwilioVerifyDemo/AccessToken/AccessTokensAPI.swift
- TwilioVerifyDemo/TwilioVerifyDemo/CreateFactor/Presenter/CreateFactorPresenter.swift
- TwilioVerifySDK.xcodeproj/project.pbxproj
- TwilioVerifySDK/TwilioSecurity/Sources/Keychain/KeychainQuery.swift
- TwilioVerifySDK/TwilioSecurity/Sources/Storage/SecureStorage.swift
- TwilioVerifySDK/TwilioVerify/Sources/API/BaseAPIClient.swift
- TwilioVerifySDK/TwilioVerify/Sources/API/FactorAPIClient.swift
- TwilioVerifySDK/TwilioVerify/Sources/Data/Storage.swift
- TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/FactorMigrations.swift
- TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/FactorRepository.swift
- TwilioVerifySDK/TwilioVerify/Sources/Extensions/URLSession+Extensions.swift
- TwilioVerifySDK/TwilioVerify/Sources/Networking/Error/NetworkError.swift
- TwilioVerifySDK/TwilioVerify/Sources/TwilioVerifyError.swift
- TwilioVerifySDKTests/TwilioSecurity/Sources/Keychain/KeychainQueryTests.swift
- TwilioVerifySDKTests/TwilioSecurity/Sources/Keychain/KeychainTests.swift
- TwilioVerifySDKTests/TwilioSecurity/Sources/Storage/SecureStorageTests.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/API/ChallengeAPIClientTests.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/API/FactorAPIClientTests.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/Data/Mocks/SecureStorageMock.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/Data/StorageTests.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/Domain/Factor/FactorRepositoryTests.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/Networking/NetworkAdapterTests.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/Networking/NetworkErrorTests.swift
- fastlane/Fastfile
- Clearing storage after reinstall will remove only factors. Previous implementation was removing all the keychain items on reinstall
- Improved network error to get Verify API error
> Version 2.0.0

- TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/FactorFacade.swift
- TwilioVerifySDK/TwilioVerify/Sources/Domain/Manager/TwilioVerify.swift
- [23614]
- Update Build Method and Secure Storage to send kSecAttrAccessGroup & kSecAttrSynchronizable.
-  
https://user-images.githubusercontent.com/4898461/148605666-1d572beb-faed-4a03-ac19-1e0879683a85.mp4
> [23614] - Update Build Method and Secure Storage to send kSecAttrAccessGroup & kSecAttrSynchronizable.

- TwilioVerifySDK/TwilioSecurity/Sources/Keychain/KeychainQuery.swift
- TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/FactorFacade.swift
- TwilioVerifySDK/TwilioVerify/Sources/Domain/Manager/TwilioVerify.swift
- TwilioVerifySDKTests/TwilioSecurity/Sources/Keychain/KeychainQueryTests.swift
- TwilioVerifySDKTests/TwilioSecurity/Sources/Keychain/KeychainTests.swift
- [23613]
- Add kSecAttrAccessGroup & kSecAttrSynchronizable properties to KeyChainQuery.
-  
| AccessGroup | Synchronizable |
|-|-|
|![Screen Shot 2022-01-05 at 4 50 07 PM](https://user-images.githubusercontent.com/4898461/148294644-22d49b75-82c6-48e4-b90d-eafad977a012.png)|![Screen Shot 2022-01-05 at 4 49 50 PM](https://user-images.githubusercontent.com/4898461/148294650-6e01734c-5f30-46a0-87c2-205e6b150915.png)|
> [23613] - Add kSecAttrAccessGroup & kSecAttrSynchronizable.

- TwilioVerifyDemo/TwilioVerifyDemo.xcodeproj/project.pbxproj
- TwilioVerifyDemo/TwilioVerifyDemo/Common/KeyChainAccessGroupHelper.swift
- TwilioVerifyDemo/TwilioVerifyDemo/TwilioVerify/TwilioVerifyAdapter.swift
- TwilioVerifyDemo/TwilioVerifyDemo/TwilioVerifyDemo.entitlements
- TwilioVerifySDK/TwilioSecurity/Sources/Keychain/KeychainQuery.swift
- TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/FactorFacade.swift
- TwilioVerifySDK/TwilioVerify/Sources/Domain/Manager/TwilioVerify.swift
- TwilioVerifySDKTests/TwilioSecurity/Sources/Keychain/KeychainQueryTests.swift
- TwilioVerifySDKTests/TwilioSecurity/Sources/Keychain/KeychainTests.swift
- [23665]
- Configure DemoApp with AccessGroup.
-
> [23665] - Configure DemoApp with AccessGroup.

- README.md
- TwilioVerifyDemo/TwilioVerifyDemo/ChallengeDetail/Presenter/ChallengeDetailPresenter.swift
- TwilioVerifySDK/TwilioVerify/Sources/Domain/Challenge/ChallengeFacade.swift
- TwilioVerifySDK/TwilioVerify/Sources/Domain/Challenge/ChallengeRepository.swift
- TwilioVerifySDK/TwilioVerify/Sources/Domain/Challenge/PushChallengeProcessor.swift
- TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/FactorFacade.swift
- TwilioVerifySDK/TwilioVerify/Sources/TwilioVerifyError.swift
- TwilioVerifySDKTests/Plans/CompleteSuite.xctestplan
- TwilioVerifySDKTests/TwilioVerify/Sources/Domain/Challenge/ChallengeFacadeTests.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/Domain/Challenge/ChallengeRepositoryTests.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/Domain/Challenge/PushChallengeProcessorTests.swift
- TwilioVerifySDKTests/TwilioVerify/Sources/Domain/Factor/FactorFacadeTests.swift
- [23983]
- Create InputException to provide more info about the reason of failure
-  feat: Improve input error to provide reason of failure
> [23983] Improve input error to provide reason of failure

- README.md
- [#####]
- ISSUE-
- NotificationExtension Readme update
-  docs: Setting up a Notification Extension
> NotificationExtension Readme update

- TwilioVerifySDK/TwilioSecurity/Sources/Keychain/Keychain.swift
- TwilioVerifySDK/TwilioSecurity/Sources/Storage/SecureStorage.swift
- TwilioVerifySDKTests/TwilioSecurity/Sources/Keychain/Mocks/KeychainMock.swift
- TwilioVerifySDKTests/TwilioSecurity/Sources/Storage/SecureStorageTests.swift
- [25408]
- Add retry for get queries  at SecureStorage.
-  fix: Add retry for keychain operations, trying to prevent 25300 keychain error code [25408]
> [25408] - Retry Implementation for Get Queries.

- .circleci/config.yml
- fastlane/Fastfile
- Update firebase config and xcode version
-  chore: Update CI config
> chore: Update CI

- fastlane/Fastfile
- [#####]
- ISSUE-
- Fix release process
chore: Fix release process
> chore: Fix release process

- fastlane/Fastfile
- [#####]
- ISSUE-
- Fix Github author for CI
chore: Fix Github author for CI
> chore: Fix Github author for CI

- fastlane/Fastfile
- [#####]
- ISSUE-
- fix release process.
chore: fix release process.
> chore: fix release process.
